# Server Configuration
server.port=8115

# Spring Application Name
spring.application.name=reports-service

# Microservice Client Target URLs
services.employee.url=http://localhost:8101
services.attendance.url=http://localhost:8112
services.leave.url=http://localhost:8113
services.payroll.url=http://localhost:8116

# Logging Configuration
logging.level.org.springframework.web=INFO
