# Server Configuration
server.port=8087

# Spring Application Name
spring.application.name=reports-service

# Microservice Client Target URLs
services.employee.url=http://localhost:8099
services.attendance.url=http://localhost:8083
services.leave.url=http://localhost:8084
services.payroll.url=http://localhost:8085

# Logging Configuration
logging.level.org.springframework.web=INFO
