-- DB Setup Script for Leave Service (Oracle 11g)

-- Drop existing tables and sequences if they exist (for clean run)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LEAVE_REQUEST CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LEAVE_TYPE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LEAVE_STATUS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE LEAVE_REQUEST_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE LEAVE_TYPE_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE LEAVE_STATUS_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create Sequences
CREATE SEQUENCE LEAVE_TYPE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE LEAVE_STATUS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE LEAVE_REQUEST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Create LEAVE_TYPE Table
CREATE TABLE LEAVE_TYPE (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(255)
);

-- Create LEAVE_STATUS Table
CREATE TABLE LEAVE_STATUS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(255)
);

-- Create LEAVE_REQUEST Table
CREATE TABLE LEAVE_REQUEST (
    ID NUMBER PRIMARY KEY,
    EMPLOYEE_ID VARCHAR2(255) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    LEAVE_TYPE_ID NUMBER NOT NULL,
    LEAVE_STATUS_ID NUMBER NOT NULL,
    REASON VARCHAR2(500),
    ADMIN_COMMENT VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_LEAVE_TYPE FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES LEAVE_TYPE(ID),
    CONSTRAINT FK_LEAVE_STATUS FOREIGN KEY (LEAVE_STATUS_ID) REFERENCES LEAVE_STATUS(ID)
);

-- Insert Initial Leave Types
INSERT INTO LEAVE_TYPE (ID, NAME, DESCRIPTION) VALUES (LEAVE_TYPE_SEQ.NEXTVAL, 'SICK', 'Sick Leave');
INSERT INTO LEAVE_TYPE (ID, NAME, DESCRIPTION) VALUES (LEAVE_TYPE_SEQ.NEXTVAL, 'CASUAL', 'Casual Leave');
INSERT INTO LEAVE_TYPE (ID, NAME, DESCRIPTION) VALUES (LEAVE_TYPE_SEQ.NEXTVAL, 'ANNUAL', 'Annual Leave');
INSERT INTO LEAVE_TYPE (ID, NAME, DESCRIPTION) VALUES (LEAVE_TYPE_SEQ.NEXTVAL, 'MATERNITY', 'Maternity Leave');
INSERT INTO LEAVE_TYPE (ID, NAME, DESCRIPTION) VALUES (LEAVE_TYPE_SEQ.NEXTVAL, 'PATERNITY', 'Paternity Leave');

-- Insert Initial Leave Statuses
INSERT INTO LEAVE_STATUS (ID, NAME, DESCRIPTION) VALUES (LEAVE_STATUS_SEQ.NEXTVAL, 'PENDING', 'Pending Approval');
INSERT INTO LEAVE_STATUS (ID, NAME, DESCRIPTION) VALUES (LEAVE_STATUS_SEQ.NEXTVAL, 'APPROVED', 'Approved by Admin');
INSERT INTO LEAVE_STATUS (ID, NAME, DESCRIPTION) VALUES (LEAVE_STATUS_SEQ.NEXTVAL, 'REJECTED', 'Rejected by Admin');

COMMIT;
