spring.application.name=attendance-service
server.port=8112

# Oracle 11g Database Connection Settings
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=df_attendance
spring.datasource.password=AttendancePass123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA/Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging levels
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
