-- ==========================================
-- SECTION 1: DATABASE USER CREATION
-- RUN THIS PORTION AS SYS OR SYSTEM USER IN ORACLE 11g (e.g., ORCL or xe database)
-- ==========================================

-- CREATE USER df_notification IDENTIFIED BY NotificationPass123;
-- GRANT CONNECT, RESOURCE, CREATE VIEW TO df_notification;
-- ALTER USER df_notification QUOTA UNLIMITED ON USERS;

-- ==========================================
-- SECTION 2: DDL SCHEMA CREATION (FOR ORACLE 11g)
-- CONNECT AS df_notification AND RUN THE FOLLOWING:
-- ==========================================

-- Drop table and sequence if they exist to allow a clean run
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE NOTIFICATION';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE NOTIFICATION_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 1. Create Sequence for NOTIFICATION ID
CREATE SEQUENCE NOTIFICATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 2. Create NOTIFICATION Table
CREATE TABLE NOTIFICATION (
    NOTIFICATION_ID NUMBER PRIMARY KEY,
    EMPLOYEE_ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    MESSAGE VARCHAR2(1000) NOT NULL,
    TYPE VARCHAR2(50) NOT NULL,
    IS_READ VARCHAR2(1) DEFAULT 'N' NOT NULL CHECK (IS_READ IN ('Y', 'N')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 3. Create Index on EMPLOYEE_ID for faster queries
CREATE INDEX IDX_NOTIFICATION_EMP ON NOTIFICATION(EMPLOYEE_ID);
