-- ==========================================
-- SECTION 1: DATABASE USER CREATION
-- RUN THIS PORTION AS SYS OR SYSTEM USER IN ORACLE 11g (e.g., ORCL database)
-- ==========================================

-- CREATE USER df_employee_admin IDENTIFIED BY AdminPass123;
-- GRANT CONNECT, RESOURCE, CREATE VIEW TO df_employee_admin;
-- ALTER USER df_employee_admin QUOTA UNLIMITED ON USERS;

-- ==========================================
-- SECTION 2: DDL SCHEMA CREATION (FOR ORACLE 11g)
-- CONNECT AS df_employee_admin AND RUN THE FOLLOWING:
-- ==========================================

-- Drop tables and sequences if they exist to allow a clean run
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE APP_USER';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_EMP_PROFILE_PIC';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DOCUMENT';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ROLE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ADDRESS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENT';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DESIGNATION';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE ROLE_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE ADDRESS_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE DEPARTMENT_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE DESIGNATION_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE DOCUMENT_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE APP_USER_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 1. Create Sequences for Auto-Incrementing IDs
CREATE SEQUENCE ROLE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ADDRESS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DEPARTMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DESIGNATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE DOCUMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE APP_USER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- 2. Create Role table
CREATE TABLE ROLE (
    ROLE_ID NUMBER PRIMARY KEY,
    ROLE_NAME VARCHAR2(20) UNIQUE NOT NULL CHECK (ROLE_NAME IN ('EMPLOYEE', 'ADMIN'))
);

-- 3. Create Address table
CREATE TABLE ADDRESS (
    ADDRESS_ID NUMBER PRIMARY KEY,
    LINE1 VARCHAR2(150) NOT NULL,
    LINE2 VARCHAR2(150),
    CITY VARCHAR2(60) NOT NULL,
    STATE VARCHAR2(60) NOT NULL,
    PIN_CODE VARCHAR2(10) NOT NULL,
    COUNTRY VARCHAR2(60) NOT NULL
);

-- 4. Create Department table
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(100) UNIQUE NOT NULL
);

-- 5. Create Designation table
CREATE TABLE DESIGNATION (
    DESIGNATION_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) UNIQUE NOT NULL
);

-- 6. Create Employee table (Employee ID is manually provided String)
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID VARCHAR2(50) PRIMARY KEY,
    FIRST_NAME VARCHAR2(60) NULL,
    LAST_NAME VARCHAR2(60) NULL,
    DOB DATE,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F', 'O')),
    PHONE VARCHAR2(15),
    ADDRESS_ID NUMBER REFERENCES ADDRESS(ADDRESS_ID) ON DELETE SET NULL,
    DEPARTMENT_ID NUMBER REFERENCES DEPARTMENT(DEPARTMENT_ID) ON DELETE SET NULL,
    DESIGNATION_ID NUMBER REFERENCES DESIGNATION(DESIGNATION_ID) ON DELETE SET NULL,
    MANAGER_ID VARCHAR2(50) REFERENCES EMPLOYEE(EMPLOYEE_ID) ON DELETE SET NULL,
    JOINING_DATE DATE NULL,
    PROFILE_PIC_FILE_ID NUMBER
);

-- 7. Create Document table
CREATE TABLE DOCUMENT (
    DOCUMENT_ID NUMBER PRIMARY KEY,
    EMPLOYEE_ID VARCHAR2(50) REFERENCES EMPLOYEE(EMPLOYEE_ID) ON DELETE CASCADE NOT NULL,
    DOC_TYPE VARCHAR2(30) NOT NULL CHECK (DOC_TYPE IN ('PHOTO', 'ID_PROOF', 'OFFER_LETTER', 'OTHER')),
    FILE_URL VARCHAR2(500) NOT NULL,
    UPLOADED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 8. Add foreign key for PROFILE_PIC_FILE_ID back to EMPLOYEE table
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMP_PROFILE_PIC FOREIGN KEY (PROFILE_PIC_FILE_ID) REFERENCES DOCUMENT(DOCUMENT_ID) ON DELETE SET NULL;

-- 9. Create AppUser table
CREATE TABLE APP_USER (
    USER_ID NUMBER PRIMARY KEY,
    EMPLOYEE_ID VARCHAR2(50) UNIQUE NOT NULL REFERENCES EMPLOYEE(EMPLOYEE_ID) ON DELETE CASCADE,
    EMAIL VARCHAR2(150) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ROLE_ID NUMBER REFERENCES ROLE(ROLE_ID) NOT NULL,
    IS_EMAIL_VERIFIED CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_EMAIL_VERIFIED IN ('Y', 'N')),
    IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL CHECK (IS_ACTIVE IN ('Y', 'N')),
    INVITE_TOKEN VARCHAR2(100) NULL,
    TOKEN_EXPIRY TIMESTAMP NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ==========================================
-- SECTION 3: SEED LOOKUP & ADMIN DATA
-- ==========================================

-- Seed Roles
INSERT INTO ROLE (ROLE_ID, ROLE_NAME) VALUES (ROLE_SEQ.NEXTVAL, 'EMPLOYEE');
INSERT INTO ROLE (ROLE_ID, ROLE_NAME) VALUES (ROLE_SEQ.NEXTVAL, 'ADMIN');

-- Seed Departments
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPT_NAME) VALUES (DEPARTMENT_SEQ.NEXTVAL, 'Engineering');
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPT_NAME) VALUES (DEPARTMENT_SEQ.NEXTVAL, 'Human Resources');
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPT_NAME) VALUES (DEPARTMENT_SEQ.NEXTVAL, 'Finance');
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPT_NAME) VALUES (DEPARTMENT_SEQ.NEXTVAL, 'Marketing');

-- Seed Designations
INSERT INTO DESIGNATION (DESIGNATION_ID, TITLE) VALUES (DESIGNATION_SEQ.NEXTVAL, 'Software Engineer');
INSERT INTO DESIGNATION (DESIGNATION_ID, TITLE) VALUES (DESIGNATION_SEQ.NEXTVAL, 'HR Manager');
INSERT INTO DESIGNATION (DESIGNATION_ID, TITLE) VALUES (DESIGNATION_SEQ.NEXTVAL, 'Financial Analyst');
INSERT INTO DESIGNATION (DESIGNATION_ID, TITLE) VALUES (DESIGNATION_SEQ.NEXTVAL, 'Marketing Specialist');

-- Seed the initial Admin user (Karthi) with String ID 'EMP-ADMIN-01'
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DOB, GENDER, PHONE, ADDRESS_ID, DEPARTMENT_ID, DESIGNATION_ID, MANAGER_ID, JOINING_DATE) 
VALUES ('EMP-ADMIN-01', 'Karthi', 'Admin', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 'M', '1234567890', NULL, 2, 2, NULL, TO_DATE('2026-08-22', 'YYYY-MM-DD'));

-- Admin Credentials (email: alonewarrior123456@gmail.com, password: "AdminPassword123" -> hashed: 24075510619a9a0f05d54c8c772dc3fa55b9e075079a42f65a19001b97950294)
INSERT INTO APP_USER (USER_ID, EMPLOYEE_ID, EMAIL, PASSWORD_HASH, ROLE_ID, IS_EMAIL_VERIFIED, IS_ACTIVE)
VALUES (APP_USER_SEQ.NEXTVAL, 'EMP-ADMIN-01', 'alonewarrior123456@gmail.com', '24075510619a9a0f05d54c8c772dc3fa55b9e075079a42f65a19001b97950294', 2, 'Y', 'Y');

COMMIT;
