-- DB Setup for Oracle 11g Express Edition (xe)
-- User: df_attendance

-- Drop existing tables/sequences if they exist to support clean re-runs
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ATTENDANCE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ATTENDANCE_STATUS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ATTENDANCE_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create ATTENDANCE_STATUS Table
CREATE TABLE ATTENDANCE_STATUS (
    STATUS_CODE VARCHAR2(20) PRIMARY KEY,
    DESCRIPTION VARCHAR2(100) NOT NULL
);

-- Insert reference values
INSERT INTO ATTENDANCE_STATUS (STATUS_CODE, DESCRIPTION) VALUES ('PRESENT', 'Employee present for full shift');
INSERT INTO ATTENDANCE_STATUS (STATUS_CODE, DESCRIPTION) VALUES ('LATE', 'Employee arrived late');
INSERT INTO ATTENDANCE_STATUS (STATUS_CODE, DESCRIPTION) VALUES ('HALFDAY', 'Employee present for half shift');
INSERT INTO ATTENDANCE_STATUS (STATUS_CODE, DESCRIPTION) VALUES ('ABSENT', 'Employee absent');
COMMIT;

-- Create ATTENDANCE Table
CREATE TABLE ATTENDANCE (
    ATTENDANCE_ID NUMBER(19,0) PRIMARY KEY,
    EMPLOYEE_ID NUMBER(19,0) NOT NULL,
    DEPARTMENT_ID NUMBER(19,0),
    WORK_DATE DATE NOT NULL,
    CHECK_IN TIMESTAMP,
    CHECK_OUT TIMESTAMP,
    STATUS_CODE VARCHAR2(20) NOT NULL,
    AUDIT_REMARK VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_ATT_STATUS FOREIGN KEY (STATUS_CODE) REFERENCES ATTENDANCE_STATUS(STATUS_CODE)
);

-- Create Sequence
CREATE SEQUENCE ATTENDANCE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
